src/Entity/Romans.php
<?php

//App/Entity/Romans
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RomansRepository")
 */
class Romans
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $auteur;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $maison_edition;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $annee_edition;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sous_genre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $breve_description;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imgLivre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imgAuteur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imgQuatrCouv;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaires", mappedBy="bookId", orphanRemoval=true)
     */
    private $commentairesId;


    public function __construct()
    {
        $this->commentairesId = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }


    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getMaisonEdition(): ?string
    {
        return $this->maison_edition;
    }

    public function setMaisonEdition(string $maison_edition): self
    {
        $this->maison_edition = $maison_edition;

        return $this;
    }

    public function getAnneeEdition(): ?string
    {
        return $this->annee_edition;
    }

    public function setAnneeEdition(string $annee_edition): self
    {
        $this->annee_edition = $annee_edition;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getSousGenre(): ?string
    {
        return $this->sous_genre;
    }

    public function setSousGenre(string $sous_genre): self
    {
        $this->sous_genre = $sous_genre;

        return $this;
    }

    public function getBreveDescription(): ?string
    {
        return $this->breve_description;
    }

    public function setBreveDescription(string $breve_description): self
    {
        $this->breve_description = $breve_description;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImgLivre(): ?string
    {
        return $this->imgLivre;
    }

    public function setImgLivre(string $imgLivre): self
    {
        $this->imgLivre = $imgLivre;

        return $this;
    }

    public function getImgAuteur(): ?string
    {
        return $this->imgAuteur;
    }

    public function setImgAuteur(string $imgAuteur): self
    {
        $this->imgAuteur = $imgAuteur;

        return $this;
    }

    public function getImgQuatrCouv(): ?string
    {
        return $this->imgQuatrCouv;
    }

    public function setImgQuatrCouv(string $imgQuatrCouv): self
    {
        $this->imgQuatrCouv = $imgQuatrCouv;

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentairesId(): Collection
    {
        return $this->commentairesId;
    }

    public function addCommentairesId(Commentaires $commentairesId): self
    {
        if (!$this->commentairesId->contains($commentairesId)) {
            $this->commentairesId[] = $commentairesId;
            $commentairesId->setBookId($this);
        }

        return $this;
    }

    public function removeCommentairesId(Commentaires $commentairesId): self
    {
        if ($this->commentairesId->contains($commentairesId)) {
            $this->commentairesId->removeElement($commentairesId);
            // set the owning side to null (unless already changed)
            if ($commentairesId->getBookId() === $this) {
                $commentairesId->setBookId(null);
            }
        }

        return $this;
    }




}

templates/pages/comment_edit.html.twig
{% extends 'general.html.twig' %}


{% block content %}
    <div class="cooming-soon-box spaceBetween">
        <div class="soon-gradient">
            <div class="map"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">

                        <div class="expand">
                            <h2>Modifier un commentaire</h2>

                        </div>
                        <div class="get-box">

                            {{ form_start(formComment) }}


                            {{ form_row(formComment.texte) }}

                            <button type="submit" class="btn btn-primary btn-inscr spaceBetween">Modifier un commentaire</button>

                            {{ form_end(formComment) }}


                        </div>
                    </div>
                    <div class="col-lg-6">
                        <p></p>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/connexion.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <div class="cooming-soon-box spaceBetween">
        <div class="soon-gradient ">
            <div class="map"></div>
            <div class="container ">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">

                        <div class="expand">
                            <h2>Connexion</h2>

                        </div>
                        <div class="get-box">

                            <form class="get-form">
                                <input type="email" placeholder="Adresse mail" /><br/><br/>
                                <input type="text" placeholder="Mot de passe" /><br/><br/>
                                <button class="btn btn-primary btn-inscr">Se connecter</button>
                            </form>

                        </div>
                    </div>
                    <div class="col-md-12">

                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/contact.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2>Nous contacter</h2>
            <p>Téléphone : 04265 48 95<br/>
                Mail : adressemail@gmail.com<br/>
                Adresse : 45 rue de l'existence 4200 Lièghe Pelgique<br/>
            </p>
        </div>
    </div>
{% endblock %}

templates/pages/description_livre.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <div class="container bookDescription spaceBetween">

        <div class="row clearfix">
            <div class="col-lg-6 col-sm-6 col-md-6 spaceBetween">
                <img class="centerImg" src="{{ asset('images/' ~ bookInfo.imgLivre) }}" alt="exemple"/>
            </div>
            <div class="col-lg-6 col-sm-6 col-md-6 spaceBetween">
                <h4 class="centerText spaceBetween">{{ bookInfo.titre }}</h4>
                <div class="col-md-6 col-sm-6 spaceBetween">
                    <div class="form-sh"> <a class="btn" href={{ path('wishListManagementPage') }}>Obtenir</a> </div>
                </div>
                <div class="col-md-6 col-sm-6 spaceBetween">
                    <div class="form-sh"> <a class="btn" href={{ path('giveListManagementPage') }}>Proposer</a> </div>
                </div>
                <h4 class="centerText spaceBetween">Description</h4>
                <p>{{ bookInfo.description }}</p>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-lg-6 col-sm-6 col-md-6 borderBox spaceBetween">
                <ul>
                    <li>Genre : {{ bookInfo.genre }}</li>
                    <li>Sous-genre : {{ bookInfo.sousGenre }}</li>
                    <li>Année d'édition : {{ bookInfo.anneeEdition }}</li>
                    <li>Maison d'édition : {{ bookInfo.maisonEdition }}</li>

                </ul>
            </div>
            <div class="col-lg-6 col-sm-6 col-md-6 spaceBetween">
                <div class="col-lg-6 col-sm-6 col-md-6">
                    <h4 class="spaceBetween"> Auteur : {{ bookInfo.auteur }}</h4>
                    <img class="centerImg" src="{{ asset('images/' ~ bookInfo.imgAuteur) }}" alt="test1"/>
                </div>
                <div class="col-lg-6 col-sm-6 col-md-6">
                    <h4 class="spaceBetween">Quatrième de couverture</h4>
                    <img class="centerImg" src="{{ asset('images/' ~ bookInfo.imgQuatrCouv) }}" alt="test2"/>
                </div>
            </div>
        </div>

        <div class="row clearfix">
        {% if is_granted('ROLE_ADMIN') %}
            <div class="col-lg-6 col-sm-6 col-md-6  spaceBetween">
                <div class="form-sh"> <a class="btn" href={{ path('editBookPage', { 'id': bookInfo.id }) }}>Modifier le roman</a> </div>
            </div>
            <div class="col-lg-6 col-sm-6 col-md-6  spaceBetween">
                <div class="form-sh"> <a class="btn" href={{ path('deleteBook', { 'id': bookInfo.id }) }}>Supprimer le roman</a> </div>
            </div>
            {% else %}
                <div class="col-sm-3 spaceUpAndDown"><p></p></div>
                <div class="col-sm-6 spaceUpAndDown"><p>Il faut être administrateur pour modifier un roman</p></div>
                <div class="col-sm-3 spaceUpAndDown"><p></p></div>
        {% endif %}
        </div>


        <hr>
        <div class="row spaceUpAndDown spaceUpBetweenCommentariesAndBookDescription">

          <div class="row clearfix spaceUpAndDown">
              <h3 class="biggerSpaceBetween">Commentaires</h3>

              {% for commentData in commentariesData %}
                  {% if commentData.bookId == bookInfo %}
              <div class="clearfix">
              <div class="col-lg-4 col-sm-4 col-md-4 spaceBetween">
                 <a href={{ path('userProfilePage', { 'id': commentData.bookId.id }) }}> <img src="{{ asset('images/' ~ commentData.userId.avatar) }}" alt="icone" /></a>
                  <a href={{ path('userProfilePage', { 'id': commentData.bookId.id }) }}><h3>{{commentData.userId.nom}} {{commentData.userId.prenom}}</h3></a>

                  <p>Date de publication :  Le {{ commentData.createdAt | date('d/m/y') }} à {{ commentData.createdAt | date('H:i') }}  </p>
              </div>
              <div class="col-lg-8 col-sm-8 col-md-8 spaceBetween">
                  <p>{{ commentData.texte }}
                  </p>
              </div>



              </div>
                      {% if is_granted('ROLE_ADMIN') %}
              <div class="clearfix">
                      <div class="col-sm-4">
                          <div class="form-sh"> <a class="btn" href={{ path('editCommentPage', { 'id': commentData.id }) }}>Modifier le commentaire</a> </div>
                      </div>
                  <div class="col-sm-2">
                      <p></p>
                  </div>
                  <div class="col-sm-4">
                      <div class="form-sh"> <a class="btn" href={{ path('deleteCommentPage', { 'id': commentData.id }) }}>Supprimer le commentaire</a> </div>
                  </div>
                  <div class="col-sm-2">
                      <p></p>
                  </div>
              </div>
                      {% endif %}
                  {% endif %}
              {% endfor %}
          </div>


        </div>


        <div class="row clearfix">
            <div class="commentary spaceBetween">

    {% if is_granted('ROLE_USER') %}
                <form action="" method="post" class="commentaryform">

                    <textarea class="commentarybox" name="comment" id="comment" rows="10" >Laissez votre commentaire ici...</textarea>
                    <input class="inputStyle" type="submit" value= "Envoyer" >


                </form>
        {% else %} <p>Il faut être connecté pour poster des commentaires !</p>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/pages/formulaire_romans.html.twig
{#templates/pages/formulaire_romans#}
{% extends 'general.html.twig' %}


{% block content %}
    <div class="cooming-soon-box spaceBetween">
        <div class="soon-gradient ">
            <div class="map"></div>
            <div class="container ">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">

                        <div class="expand">
                            <h2>Ajouter un roman</h2>

                        </div>
                        <div class="get-box">

                            {{ form_start(formBook) }}

                            {{ form_row(formBook.titre) }}
                            {{ form_row(formBook.auteur) }}
                            {{ form_row(formBook.maison_edition) }}
                            {{ form_row(formBook.annee_edition) }}
                            {{ form_row(formBook.genre) }}
                            {{ form_row(formBook.sous_genre) }}
                            {{ form_row(formBook.breve_description) }}
                            {{ form_row(formBook.description) }}
                            {{ form_row(formBook.imgLivreFichier) }}
                            {{ form_row(formBook.imgAuteurFichier) }}
                            {{ form_row(formBook.imgQuatrCouvFichier) }}

                            <button type="submit" class="btn btn-primary btn-inscr spaceBetween">
                                Ajouter un roman
                            </button>

                            {{ form_end(formBook) }}


                        </div>
                    </div>
                    <div class="col-md-12">

                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/gestion_liste_proposition.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <div class="furniture-box">
        <div class="container">

            <div class="row">
                <div class="furniture-main">
                    <h4 class="centerText spaceBetween">Liste romans proposés</h4>

                    <div class="row clearfix">

                        <div class="col-lg-12 col-sm-12 col-md-12 spaceBetween">
                            <div class="col-lg-4 col-sm-6 col-md-4">

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <img class="spaceBetween" src="images/couverture_2.jpg" alt="image livre 1" />
                                    <h5>Titre roman</h5>
                                </div>

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <input class="inputStyle" type="button" value= "Supprimer le livre" >
                                </div>


                            </div>
                            <div class="col-lg-4 col-sm-6 col-md-4">

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <img class="spaceBetween" src="images/couverture_3.jpg" alt="image livre 2" />
                                    <h5>Titre roman</h5>
                                </div>

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <input class="inputStyle" type="button" value= "Supprimer le livre" >
                                </div>

                            </div>


                            <div class="col-lg-4 col-sm-6 col-md-4">

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <img class="spaceBetween" src="images/couverture_4.jpg" alt="image livre 3" />
                                    <h5>Titre roman</h5>
                                </div>

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <input class="inputStyle" type="button" value= "Supprimer le livre" >
                                </div>

                            </div>
                        </div>


                        </div>

                        <div class="col-lg-3 col-sm-3 col-md-3"></div>

                        <div class="col-lg-6 col-sm-6 col-md-6 spaceBetween">
                            <div class="form-sh"> <a class="btn" href={{ path('bookSearchListPage') }}>Ajouter un roman</a> </div>
                        </div>

                        <div class="col-lg-3 col-sm-3 col-md-3"></div>

                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/gestion_liste_souhait.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <div class="furniture-box">
        <div class="container">

            <div class="row">
                <div class="furniture-main">
                    <h4 class="centerText spaceBetween">Liste romans souhaités</h4>

                    <div class="row clearfix">

                        <div class="col-lg-12 col-sm-12 col-md-12 spaceBetween">
                            <div class="col-lg-4 col-sm-6 col-md-4">

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <img class="spaceBetween" src="images/couverture_2.jpg" alt="image livre 1" />
                                    <h5>Titre roman</h5>
                                </div>

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <input class="inputStyle" type="button" value= "Supprimer le livre" >
                                </div>


                            </div>
                            <div class="col-lg-4 col-sm-6 col-md-4">

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <img class="spaceBetween" src="images/couverture_3.jpg" alt="image livre 2" />
                                    <h5>Titre roman</h5>
                                </div>

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <input class="inputStyle" type="button" value= "Supprimer le livre" >
                                </div>

                            </div>


                            <div class="col-lg-4 col-sm-6 col-md-4">

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <img class="spaceBetween" src="images/couverture_4.jpg" alt="image livre 3" />
                                    <h5>Titre roman</h5>
                                </div>

                                <div class="col-lg-6 col-sm-6 col-md-6">
                                    <input class="inputStyle" type="button" value= "Supprimer le livre" >
                                </div>

                            </div>
                        </div>


                        </div>

                        <div class="col-lg-3 col-sm-3 col-md-3"></div>

                        <div class="col-lg-6 col-sm-6 col-md-6 spaceBetween">
                            <div class="form-sh"> <a class="btn" href={{ path('bookSearchListPage') }}>Ajouter un roman</a> </div>
                        </div>

                        <div class="col-lg-3 col-sm-3 col-md-3"></div>

                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/index.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <div class="main-product">
        <div class="container">
            <div class="row clearfix first-paragraph">
                <p class="first-mass-text">Tressaillir, pousser un cri ; c'était surtout pour les destinataires.
                    Posée à ravir, et, laissez-moi vous exposer les arguments une dernière fois et appela mon numéro.
                    Entends-tu, ribaude infâme, je te la destinais, avait dit en mourant, et on leur explique que le pare-chocs arrière.
                    Jusque-là ça me gênerait de savoir à qui était ce client qui s'oubliait à quelque inutile caresse, il devint morose et dur.
                    Valait mieux que toute ma conduite, et tous ses désirs ; oui, oui...
                    Douce voix un peu altérée que quand elle l'avait entourée dune auréole de lumière éblouissante autour de lui,
                    m'avait produit exactement le même cas que moi de la nature la plus encourageante.
                    Sait-on pourquoi le vent manquait-il à cette magnifique expérience ? Rasé comme un ponton,
                    et je mettrai mes paroles dans l'intention d'envelopper la terre entière passait là,
                    ig viewpas du côté de la société en question venait de s'évanouir.
                </p>
            </div>
            <div class="row clearfix">
                {% for indexBook in indexBooks %}
                <div class="col-lg-3 col-sm-6 col-md-3">
                    <a href={{ path('bookDescriptionPage', { 'id': indexBook.id }) }}>
                        <div class="box-img">
                            <h4>{{ indexBook.titre }}</h4>
                            <img src="{{ asset('images/' ~ indexBook.imgLivre )}}" alt="index book img" />
                            <p>{{ indexBook.breveDescription}}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}


                <div class="categories_link">
                    <a href={{ path('bookSearchListPage') }}>Accéder à la liste de tous les livres</a>
                </div>
            </div>
        </div>
    </div>


    <div class="products_exciting_box">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 wow fadeIn" data-wow-delay="0.2s">
                    <div class="exciting_box f_pd">

                        <h4>Trouver les romans qui vous intéressent à prix réduits!
                        </h4>
                        <p> Surveillez-vous et n'oubliez pas que je boive encore ! Coup sur coup les échantillons de sang ou autres. Sera-t-il défendu au phalanstère de capitaliser et de placer sa poitrine contre la bouche de la soirée. Suivez ce corridor, dont il fut accablé : de quart d'heure. Allons-y pour la dernière fois : il la croyait, elle se trouva sur le bord même de la firme.
                        </p>
                        <img class="centerImg" src="images/argent_economie.jpg" class="icon-small" alt="" />
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 wow fadeIn" data-wow-delay="0.4s">
                    <div class="exciting_box l_pd">

                        <h4><strong>Faites de nouvelles découvertes</h4>
                        <p>Ceci bien établi, montra une haine mortelle, parce qu'alors les combinaisons même les plus sincères sont parfois le jeu d'oie, je me rendis ensuite à mon logis. Jadis, la nuit revint, la petite chambre haute, mais modérée. Machinalement, elle s'écartait à plus de trois jours, de demeurer dans la maison ? Magie et religion divergent alors à partir d'eau non bénite sur la tête et vit qu'il était tombé dans le ruisseau.
                        </p>
                        <img class="centerImg" src="images/Découvertes_Gallimard_(les_dos)_ⅩⅥ.jpg" class="icon-small" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/inscription.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <div class="cooming-soon-box spaceBetween">
        <div class="soon-gradient">
            <div class="map"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">

                        <div class="expand">
                            <h2>Inscription</h2>

                        </div>
                        <div class="get-box">

                            {{ form_start(registrationForm) }}

                            {{ form_row(registrationForm.nom) }}
                            {{ form_row(registrationForm.prenom) }}
                            {{ form_row(registrationForm.rue) }}
                            {{ form_row(registrationForm.cp) }}
                            {{ form_row(registrationForm.ville) }}
                            {{ form_row(registrationForm.phone) }}
                            {{ form_row(registrationForm.email) }}
                            {{ form_row(registrationForm.username) }}
                            {{ form_row(registrationForm.password) }}

                            <button class="btn btn-primary btn-inscr">S'incrire</button>
                            {{ form_end(registrationForm) }}



                        </div>
                    </div>
                    <div class="col-md-12">

                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/liste_membres.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <div class="section-how-it-works">
        <div class="container">
            <div class="row">

                <div class="clearfix">
                    <div class="col-lg-6 col-sm-6 col-md-6 spaceBetween">
                        <h4>Liste utilisateurs</h4>
                    </div>

                    <div class="col-lg-4 col-sm-4 col-md-4 spaceBetween">
                        <p></p>

                    </div>


                    <div class="col-lg-2 col-sm-2 col-md-2 spaceBetween">
                        <input class="inputStyle userListInputStyle" type="submit" value= "Envoyer" >
                    </div>
                </div>
                {% for userMember in userList %}
                <div class="clearfix">
                    <div class="col-lg-4 col-sm-4 col-md-4 spaceBetween">
                        <a href="{{ path('userProfilePage', { 'id': userMember.id }) }}">
                        <img class="userAvatar" src="{{asset('images/' ~userMember.avatar)}}" alt="user icon" />
                        <h4>{{ userMember.username }}</h4>
                        </a>
                    </div>


                    <div class="col-lg-8 col-sm-8 col-md-8 spaceBetween">
                        <p></p>
                    </div>
                </div>
                {% endfor %}




            </div>
        </div>
    </div>
{% endblock %}

templates/pages/liste_romans_recherche.html.twig
{% extends 'general.html.twig' %}

{% block content %}
    <div class="page-content-product spaceBetween">
        <div class="main-product">
            <div class="container">



                <div class="row ">
                    {%  for searchListBook in searchListBooks %}

                    <div class="col-lg-3 col-sm-3 col-md-3 bookBoxHeight clearfix">
                        <a href={{ path('bookDescriptionPage', { 'id': searchListBook.id }) }}>
                            <div class="box-img">
                                <h4>{{ searchListBook.titre }}</h4>
                                <img src="{{ asset('images/' ~ searchListBook.imgLivre) }}" alt="index book img" />
                                <p>{{ searchListBook.breveDescription}}</p>
                            </div>
                        </a>
                    </div>

                    {% endfor %}
                </div>




        </div>
    </div>
{% endblock %}

templates/pages/user_edit.html.twig
{% extends 'general.html.twig' %}


{% block content %}
    <div class="cooming-soon-box spaceBetween">
        <div class="soon-gradient ">
            <div class="map"></div>
            <div class="container ">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">

                        <div class="expand">
                            <h2>Modifier un utilisateur</h2>

                        </div>
                        <div class="get-box">

                            {{ form_start(formUser) }}


                            {{ form_row(formUser.nom) }}
                            {{ form_row(formUser.prenom) }}
                            {{ form_row(formUser.rue) }}
                            {{ form_row(formUser.cp) }}
                            {{ form_row(formUser.ville) }}
                            {{ form_row(formUser.phone) }}
                            {{ form_row(formUser.email) }}
                            {{ form_row(formUser.username) }}
                            {{ form_row(formUser.password) }}

                            <button type="submit" class="btn btn-primary btn-inscr spaceBetween">Modifier un commentaire</button>

                            {{ form_end(formUser) }}


                        </div>
                    </div>
                    <div class="col-md-12">

                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}